'use client'

import React from 'react'
import Link from 'next/link'
import { ArrowLeft, Package, FileText, Code, Mail, BarChart3, Image, Download, Eye, Sparkles } from 'lucide-react'

export default function DeliverablesPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <Link 
              href="/docs"
              className="inline-flex items-center text-blue-600 hover:text-blue-800 transition-colors mb-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Documentation
            </Link>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Deliverables & Assets</h1>
            <p className="text-gray-600">Professional outputs generated by AI agents from task completion</p>
          </div>

          <div className="bg-white rounded-xl border p-8">
            {/* Overview */}
            <section className="mb-12">
              <div className="bg-green-50 rounded-lg p-6 border border-green-200 mb-6">
                <div className="flex items-center space-x-3">
                  <Package className="w-6 h-6 text-green-600" />
                  <div>
                    <h3 className="text-lg font-semibold text-green-900">Dual-Format Architecture</h3>
                    <p className="text-green-700 mt-1">
                      Deliverables use AI-driven transformation to convert raw task outputs into professional, 
                      business-ready formats with confidence scoring and fallback mechanisms.
                    </p>
                  </div>
                </div>
              </div>

              <div className="prose prose-lg max-w-none">
                <p>
                  Deliverables are the tangible outcomes of task execution—professional documents, strategies, 
                  code, content, and assets that directly serve business objectives. The system uses advanced 
                  AI transformation to ensure outputs are business-ready, not raw technical data.
                </p>
              </div>
            </section>

            {/* Deliverable Types */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                <Sparkles className="w-6 h-6 mr-3 text-indigo-600" />
                Deliverable Types
              </h2>

              <div className="grid md:grid-cols-2 gap-6 mb-8">
                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <FileText className="w-6 h-6 text-blue-600" />
                    <h3 className="font-semibold text-gray-900">Content Assets</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Blog posts and articles</li>
                    <li>• Marketing copy and campaigns</li>
                    <li>• Email sequences and templates</li>
                    <li>• Social media content plans</li>
                    <li>• Product descriptions</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-blue-50 rounded text-xs text-blue-800">
                    <strong>AI Enhancement:</strong> Grammar, tone optimization, SEO analysis
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <BarChart3 className="w-6 h-6 text-purple-600" />
                    <h3 className="font-semibold text-gray-900">Strategic Documents</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Business plans and strategies</li>
                    <li>• Market analysis reports</li>
                    <li>• Competitive intelligence</li>
                    <li>• Go-to-market plans</li>
                    <li>• ROI projections</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-purple-50 rounded text-xs text-purple-800">
                    <strong>AI Enhancement:</strong> Data visualization, executive summaries
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <Code className="w-6 h-6 text-green-600" />
                    <h3 className="font-semibold text-gray-900">Technical Assets</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Code implementations</li>
                    <li>• API documentation</li>
                    <li>• System architectures</li>
                    <li>• Configuration files</li>
                    <li>• Database schemas</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-green-50 rounded text-xs text-green-800">
                    <strong>AI Enhancement:</strong> Code optimization, documentation generation
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <Mail className="w-6 h-6 text-orange-600" />
                    <h3 className="font-semibold text-gray-900">Communication Templates</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Client presentations</li>
                    <li>• Proposal templates</li>
                    <li>• Meeting agendas</li>
                    <li>• Status reports</li>
                    <li>• Onboarding materials</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-orange-50 rounded text-xs text-orange-800">
                    <strong>AI Enhancement:</strong> Professional formatting, brand alignment
                  </div>
                </div>
              </div>
            </section>

            {/* Dual-Format System */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                <Eye className="w-6 h-6 mr-3 text-indigo-600" />
                AI-Driven Display Transformation
              </h2>

              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 border border-blue-200 mb-6">
                <div className="flex items-start space-x-4">
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-blue-900 mb-2">Execution vs Display Format</h3>
                    <p className="text-blue-800 text-sm">
                      Raw JSON outputs are transformed into professional HTML/Markdown with AI analysis, 
                      confidence scoring, and graceful fallbacks for optimal user experience.
                    </p>
                  </div>
                  <div className="bg-white rounded-lg p-3 border border-blue-300">
                    <div className="text-xs text-center">
                      <div className="font-semibold text-blue-900">AI Confidence</div>
                      <div className="text-2xl font-bold text-green-600">87%</div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-gray-50 rounded-lg p-6">
                  <h4 className="font-semibold text-gray-900 mb-4 flex items-center">
                    <Code className="w-4 h-4 mr-2 text-gray-600" />
                    Execution Format (JSON)
                  </h4>
                  <div className="bg-gray-900 rounded p-4 text-sm">
                    <pre className="text-green-400 overflow-x-auto">
                      <code>{`{
  "content": {
    "subject": "Business Proposal",
    "body": "Dear Client...",
    "attachments": ["deck.pdf"]
  },
  "metadata": {
    "type": "email_template",
    "priority": "high"
  }
}`}</code>
                    </pre>
                  </div>
                  <p className="text-xs text-gray-600 mt-2">Raw system data for processing</p>
                </div>

                <div className="bg-gray-50 rounded-lg p-6">
                  <h4 className="font-semibold text-gray-900 mb-4 flex items-center">
                    <Eye className="w-4 h-4 mr-2 text-gray-600" />
                    Display Format (HTML)
                  </h4>
                  <div className="bg-white border rounded p-4 text-sm">
                    <div className="space-y-2">
                      <h5 className="font-semibold text-gray-900">📧 Business Proposal Email</h5>
                      <p className="text-gray-600"><strong>Subject:</strong> Business Proposal</p>
                      <div className="bg-gray-50 p-3 rounded">
                        <p className="text-gray-700">Dear Client,</p>
                        <p className="text-gray-600 text-xs mt-2">Content body...</p>
                      </div>
                      <p className="text-xs text-blue-600">📎 Attachment: deck.pdf</p>
                    </div>
                  </div>
                  <p className="text-xs text-gray-600 mt-2">Professional user-facing display</p>
                </div>
              </div>
            </section>

            {/* Quality Assurance */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Quality Assurance Pipeline</h2>

              <div className="space-y-6">
                <div className="bg-gradient-to-r from-green-50 to-green-100 border border-green-200 rounded-lg p-6">
                  <div className="flex items-center space-x-3 mb-4">
                    <div className="w-8 h-8 bg-green-600 rounded-full flex items-center justify-center">
                      <span className="text-white font-bold text-sm">1</span>
                    </div>
                    <h3 className="font-semibold text-green-900">Content Validation</h3>
                  </div>
                  <div className="grid md:grid-cols-3 gap-4 text-sm">
                    <div>
                      <h4 className="font-semibold text-green-800 mb-1">Authenticity Check</h4>
                      <p className="text-green-700">AI detects placeholder content, Lorem ipsum, and generic templates</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-green-800 mb-1">Completeness</h4>
                      <p className="text-green-700">Ensures all required sections and data points are present</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-green-800 mb-1">Relevance Score</h4>
                      <p className="text-green-700">Semantic alignment with original goal and requirements</p>
                    </div>
                  </div>
                </div>

                <div className="bg-gradient-to-r from-blue-50 to-blue-100 border border-blue-200 rounded-lg p-6">
                  <div className="flex items-center space-x-3 mb-4">
                    <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center">
                      <span className="text-white font-bold text-sm">2</span>
                    </div>
                    <h3 className="font-semibold text-blue-900">Professional Enhancement</h3>
                  </div>
                  <div className="grid md:grid-cols-3 gap-4 text-sm">
                    <div>
                      <h4 className="font-semibold text-blue-800 mb-1">Format Optimization</h4>
                      <p className="text-blue-700">Consistent styling, headers, bullet points, and structure</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-blue-800 mb-1">Brand Alignment</h4>
                      <p className="text-blue-700">Tone, voice, and terminology consistency</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-blue-800 mb-1">Business Context</h4>
                      <p className="text-blue-700">Industry-specific language and best practices</p>
                    </div>
                  </div>
                </div>

                <div className="bg-gradient-to-r from-purple-50 to-purple-100 border border-purple-200 rounded-lg p-6">
                  <div className="flex items-center space-x-3 mb-4">
                    <div className="w-8 h-8 bg-purple-600 rounded-full flex items-center justify-center">
                      <span className="text-white font-bold text-sm">3</span>
                    </div>
                    <h3 className="font-semibold text-purple-900">Delivery Optimization</h3>
                  </div>
                  <div className="grid md:grid-cols-3 gap-4 text-sm">
                    <div>
                      <h4 className="font-semibold text-purple-800 mb-1">Multi-Format Export</h4>
                      <p className="text-purple-700">PDF, DOCX, HTML, Markdown generation</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-purple-800 mb-1">Version Control</h4>
                      <p className="text-purple-700">Revision tracking and change history</p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-purple-800 mb-1">Access Control</h4>
                      <p className="text-purple-700">Workspace permissions and sharing settings</p>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Goal-Deliverable Mapping */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">AI Goal Matcher System</h2>

              <div className="bg-yellow-50 rounded-lg p-6 border border-yellow-200 mb-6">
                <div className="flex items-start space-x-3">
                  <Sparkles className="w-6 h-6 text-yellow-600 mt-1" />
                  <div>
                    <h3 className="text-lg font-semibold text-yellow-900">Semantic Goal Association</h3>
                    <p className="text-yellow-700 mt-1">
                      AI analyzes deliverable content and goal descriptions to ensure proper association using 
                      semantic matching with 90%+ confidence scoring.
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <h4 className="font-semibold text-gray-900">Matching Process</h4>
                  <div className="space-y-3">
                    <div className="flex items-center space-x-3">
                      <div className="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-xs font-bold text-blue-600">1</div>
                      <span className="text-sm text-gray-600">Content analysis and keyword extraction</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <div className="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-xs font-bold text-blue-600">2</div>
                      <span className="text-sm text-gray-600">Semantic similarity scoring across active goals</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <div className="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-xs font-bold text-blue-600">3</div>
                      <span className="text-sm text-gray-600">Confidence validation and reasoning generation</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <div className="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-xs font-bold text-blue-600">4</div>
                      <span className="text-sm text-gray-600">Memory pattern storage for future matching</span>
                    </div>
                  </div>
                </div>

                <div className="bg-gray-50 rounded-lg p-4">
                  <h4 className="font-semibold text-gray-900 mb-3">Example Match Result</h4>
                  <div className="space-y-3 text-sm">
                    <div>
                      <div className="font-semibold text-gray-700">Deliverable:</div>
                      <div className="text-gray-600">"Email sequence for SaaS onboarding"</div>
                    </div>
                    <div>
                      <div className="font-semibold text-gray-700">Matched Goal:</div>
                      <div className="text-gray-600">"Develop user retention strategy"</div>
                    </div>
                    <div>
                      <div className="font-semibold text-gray-700">AI Reasoning:</div>
                      <div className="text-gray-600 italic">"Email onboarding directly impacts user retention through engagement and product adoption"</div>
                    </div>
                    <div className="flex justify-between items-center pt-2 border-t">
                      <span className="font-semibold text-gray-700">Confidence:</span>
                      <span className="font-bold text-green-600">94%</span>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Technical Implementation */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Technical Implementation</h2>

              <div className="bg-gray-900 rounded-lg p-6 text-white mb-6">
                <h3 className="text-lg font-semibold mb-4 text-green-400">Database Schema</h3>
                <pre className="text-sm overflow-x-auto">
                  <code>{`-- Dual-format deliverable storage
CREATE TABLE asset_artifacts (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL,
  goal_id UUID REFERENCES workspace_goals(id),
  
  -- Execution format (system processing)
  content JSONB NOT NULL,
  
  -- Display format (user presentation)  
  display_content TEXT,
  display_format VARCHAR(20) DEFAULT 'html',
  display_quality_score FLOAT DEFAULT 0.0,
  transformation_timestamp TIMESTAMP,
  auto_display_generated BOOLEAN DEFAULT false,
  
  -- Metadata
  title VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);`}</code>
                </pre>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                  <h4 className="font-semibold text-blue-900 mb-3">AI Services Integration</h4>
                  <ul className="text-sm text-blue-800 space-y-1">
                    <li>• <code>ai_content_display_transformer.py</code></li>
                    <li>• <code>ai_goal_matcher.py</code></li>
                    <li>• <code>content_aware_learning_engine.py</code></li>
                    <li>• Rate limiting and fallback handling</li>
                  </ul>
                </div>

                <div className="bg-green-50 rounded-lg p-6 border border-green-200">
                  <h4 className="font-semibold text-green-900 mb-3">API Endpoints</h4>
                  <ul className="text-sm text-green-800 space-y-1">
                    <li>• <code>GET /api/deliverables/workspace/{id}</code></li>
                    <li>• <code>GET /api/unified-assets/workspace/{id}</code></li>
                    <li>• <code>POST /api/deliverables/{id}/transform</code></li>
                    <li>• <code>GET /api/deliverables/{id}/download</code></li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Performance & Reliability */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Performance & Reliability</h2>

              <div className="grid md:grid-cols-3 gap-6">
                <div className="bg-green-50 rounded-lg p-6 text-center border border-green-200">
                  <Download className="w-8 h-8 text-green-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-green-900">< 1.5s</div>
                  <div className="text-sm text-green-700">AI transformation time</div>
                </div>

                <div className="bg-blue-50 rounded-lg p-6 text-center border border-blue-200">
                  <Sparkles className="w-8 h-8 text-blue-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-blue-900">85%+</div>
                  <div className="text-sm text-blue-700">AI confidence average</div>
                </div>

                <div className="bg-purple-50 rounded-lg p-6 text-center border border-purple-200">
                  <Package className="w-8 h-8 text-purple-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-purple-900">100%</div>
                  <div className="text-sm text-purple-700">Fallback reliability</div>
                </div>
              </div>

              <div className="mt-6 bg-gray-50 rounded-lg p-6">
                <h4 className="font-semibold text-gray-900 mb-3">Optimization Features</h4>
                <div className="grid md:grid-cols-2 gap-6 text-sm text-gray-600">
                  <div>
                    <h5 className="font-semibold text-gray-800 mb-2">Caching Strategy</h5>
                    <ul className="space-y-1">
                      <li>• Transformation result caching</li>
                      <li>• Goal matching pattern storage</li>
                      <li>• Asset artifact optimization</li>
                    </ul>
                  </div>
                  <div>
                    <h5 className="font-semibold text-gray-800 mb-2">Error Handling</h5>
                    <ul className="space-y-1">
                      <li>• Graceful AI service degradation</li>
                      <li>• Rule-based fallback systems</li>
                      <li>• Quality score confidence thresholds</li>
                    </ul>
                  </div>
                </div>
              </div>
            </section>

            {/* Related Concepts */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Related Concepts</h2>
              
              <div className="grid md:grid-cols-3 gap-4">
                <Link 
                  href="/docs/core-concepts/tasks"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <Package className="w-5 h-5 text-blue-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Tasks</h3>
                  <p className="text-sm text-gray-600">Task execution and lifecycle</p>
                </Link>

                <Link 
                  href="/docs/core-concepts/goals"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <BarChart3 className="w-5 h-5 text-green-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Goals</h3>
                  <p className="text-sm text-gray-600">Goal-deliverable mapping</p>
                </Link>

                <Link 
                  href="/docs/ai-architecture/quality-gates"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <Sparkles className="w-5 h-5 text-purple-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Quality Gates</h3>
                  <p className="text-sm text-gray-600">Quality assurance pipeline</p>
                </Link>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}