'use client'

import React from 'react'
import Link from 'next/link'
import { ArrowLeft, Package, FileText, Code, Mail, BarChart3, Image, Download, Eye, Sparkles } from 'lucide-react'

export default function DeliverablesPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <Link 
              href="/docs"
              className="inline-flex items-center text-blue-600 hover:text-blue-800 transition-colors mb-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Documentation
            </Link>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Deliverables & Assets</h1>
            <p className="text-gray-600">Professional outputs generated by AI agents from task completion</p>
          </div>

          <div className="bg-white rounded-xl border p-8">
            {/* Overview */}
            <section className="mb-12">
              <div className="bg-green-50 rounded-lg p-6 border border-green-200 mb-6">
                <div className="flex items-center space-x-3">
                  <Package className="w-6 h-6 text-green-600" />
                  <div>
                    <h3 className="text-lg font-semibold text-green-900">Dual-Format Architecture</h3>
                    <p className="text-green-700 mt-1">
                      Deliverables use AI-driven transformation to convert raw task outputs into professional, 
                      business-ready formats with confidence scoring and fallback mechanisms.
                    </p>
                  </div>
                </div>
              </div>

              <div className="prose prose-lg max-w-none">
                <p>
                  Deliverables are the tangible outcomes of task execution—professional documents, strategies, 
                  code, content, and assets that directly serve business objectives. The system uses advanced 
                  AI transformation to ensure outputs are business-ready, not raw technical data.
                </p>
              </div>
            </section>

            {/* Deliverable Types */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                <Sparkles className="w-6 h-6 mr-3 text-indigo-600" />
                Deliverable Types
              </h2>

              <div className="grid md:grid-cols-2 gap-6 mb-8">
                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <FileText className="w-6 h-6 text-blue-600" />
                    <h3 className="font-semibold text-gray-900">Content Assets</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Blog posts and articles</li>
                    <li>• Marketing copy and campaigns</li>
                    <li>• Email sequences and templates</li>
                    <li>• Social media content plans</li>
                    <li>• Product descriptions</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-blue-50 rounded text-xs text-blue-800">
                    <strong>AI Enhancement:</strong> Grammar, tone optimization, SEO analysis
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <BarChart3 className="w-6 h-6 text-purple-600" />
                    <h3 className="font-semibold text-gray-900">Strategic Documents</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Business plans and strategies</li>
                    <li>• Market analysis reports</li>
                    <li>• Competitive intelligence</li>
                    <li>• Go-to-market plans</li>
                    <li>• ROI projections</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-purple-50 rounded text-xs text-purple-800">
                    <strong>AI Enhancement:</strong> Data visualization, executive summaries
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <Code className="w-6 h-6 text-green-600" />
                    <h3 className="font-semibold text-gray-900">Technical Assets</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Code implementations</li>
                    <li>• API documentation</li>
                    <li>• System architectures</li>
                    <li>• Configuration files</li>
                    <li>• Database schemas</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-green-50 rounded text-xs text-green-800">
                    <strong>AI Enhancement:</strong> Code optimization, documentation generation
                  </div>
                </div>

                <div className="border rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-center space-x-3 mb-4">
                    <Mail className="w-6 h-6 text-orange-600" />
                    <h3 className="font-semibold text-gray-900">Communication Templates</h3>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-2">
                    <li>• Client presentations</li>
                    <li>• Proposal templates</li>
                    <li>• Meeting agendas</li>
                    <li>• Status reports</li>
                    <li>• Onboarding materials</li>
                  </ul>
                  <div className="mt-4 px-3 py-2 bg-orange-50 rounded text-xs text-orange-800">
                    <strong>AI Enhancement:</strong> Professional formatting, brand alignment
                  </div>
                </div>
              </div>
            </section>

            {/* Performance & Reliability */}
            <section className="mb-12">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Performance & Reliability</h2>

              <div className="grid md:grid-cols-3 gap-6">
                <div className="bg-green-50 rounded-lg p-6 text-center border border-green-200">
                  <Download className="w-8 h-8 text-green-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-green-900">1.5s</div>
                  <div className="text-sm text-green-700">AI transformation time</div>
                </div>

                <div className="bg-blue-50 rounded-lg p-6 text-center border border-blue-200">
                  <Sparkles className="w-8 h-8 text-blue-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-blue-900">85%+</div>
                  <div className="text-sm text-blue-700">AI confidence average</div>
                </div>

                <div className="bg-purple-50 rounded-lg p-6 text-center border border-purple-200">
                  <Package className="w-8 h-8 text-purple-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-purple-900">100%</div>
                  <div className="text-sm text-purple-700">Fallback reliability</div>
                </div>
              </div>
            </section>

            {/* Related Concepts */}
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Related Concepts</h2>
              
              <div className="grid md:grid-cols-3 gap-4">
                <Link 
                  href="/docs/core-concepts/tasks"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <Package className="w-5 h-5 text-blue-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Tasks</h3>
                  <p className="text-sm text-gray-600">Task execution and lifecycle</p>
                </Link>

                <Link 
                  href="/docs/core-concepts/goals"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <BarChart3 className="w-5 h-5 text-green-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Goals</h3>
                  <p className="text-sm text-gray-600">Goal-deliverable mapping</p>
                </Link>

                <Link 
                  href="/docs/ai-architecture/quality-gates"
                  className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
                >
                  <Sparkles className="w-5 h-5 text-purple-600 mb-2" />
                  <h3 className="font-semibold text-gray-900 mb-1">Quality Gates</h3>
                  <p className="text-sm text-gray-600">Quality assurance pipeline</p>
                </Link>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}